services:
  singleton:
    image: mcr.microsoft.com/dotnet/sdk:9.0
#    platform: linux/arm64
    restart: on-failure
    ports:
      - 8085:80
    command: ["dotnet", "watch", "run", "--project", "/app"]
    networks:
      - radx
    volumes:
      - .:/app
      - /app/obj # <- directory won't be mounted
      - /app/bin # <- directory won't be mounted
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  radx:
    name: radx
    external: true